// Long-duration stress-test harness for the reasoning pipeline against the REAL Ollama provider.
//
// Unlike benchmarks/e2e/pipeline.ts (which always installs a deterministic fetch stub and
// hardcodes provider:'openai', model:'gpt-4o-mini', apiKey:'test-key' — see fetchStub.ts), this
// script never installs any fetch stub. Real `fetch` hits the real network, and
// decisionIntelligence is generated by a real Ollama-compatible endpoint (config sourced from
// env — see src/reasoning/providers/config.ts / ollamaProvider.ts / providers/types.ts).
//
// SAFETY NOTE ON EXECUTION: `executeRoute` (src/reasoning/routeExecutionEngine/engine.ts) never
// signs or submits a transaction under any registry — its own header comment says so explicitly
// ("never signs or submits"), and it only ever produces an unsigned XDR + simulation result. Even
// this repo's own "LIVE" testnet test (src/__tests__/blendLiveTestnet.test.ts) only simulates,
// never submits. Given that, and to avoid needing a funded testnet account/secret for a stress
// script whose whole point is the reasoning stage, this script reuses the SAME synthetic protocol
// registry the existing e2e benchmark harness uses (benchmarks/e2e/registry.ts
// buildProtocolRegistry — deterministic test doubles over the soroswap adapter). Execution/route/
// outcome stages are therefore SIMULATED, not a real broadcast, while decisionIntelligence uses
// the real Ollama LLM end to end.
//
// Usage:
//   tsx --env-file=.env scripts/longRunStress.ts --duration-minutes=2   (bounded smoke test)
//   tsx --env-file=.env scripts/longRunStress.ts                        (runs until killed)

import { appendFileSync, mkdirSync } from 'fs';
import path from 'path';

import { InMemoryEpisodicProvider } from '../src/memoryLayer/providers/inMemoryEpisodicProvider.js';
import { InMemorySemanticProvider } from '../src/memoryLayer/providers/inMemorySemanticProvider.js';
import { InMemoryWorkingProvider } from '../src/memoryLayer/providers/inMemoryWorkingProvider.js';
import { buildReasoningContext } from '../src/reasoning/contextBuilder.js';
import { buildPrompt } from '../src/reasoning/promptBuilder.js';
import { generateDecisionIntelligence } from '../src/reasoning/decisionIntelligence/orchestrator.js';
import { verifyDecision } from '../src/reasoning/verification/verify.js';
import { buildExecutionPlan } from '../src/reasoning/executionPlanner/planner.js';
import { computeRoutesForPlan } from '../src/reasoning/routeEngine/planAdapter.js';
import { executeRoute } from '../src/reasoning/routeExecutionEngine/engine.js';
import { recordOutcome } from '../src/reasoning/outcomeRecorder/recorder.js';
import { writeMemory, type WriteMemoryProviders } from '../src/reasoning/memoryWriter/writer.js';
import { computeLearningSnapshot } from '../src/reasoning/learningEngine/engine.js';
import { sha256 } from '../src/reasoning/hashing.js';
import { buildProtocolRegistry } from '../benchmarks/e2e/registry.js';
import { buildFixtures, FIXTURE_ASSET, FIXTURE_OUTPUT_ASSET, type PipelineFixtures } from '../benchmarks/e2e/fixtures.js';
import type { ProviderCallConfig } from '../src/reasoning/providers/types.js';

// ── CLI args ──────────────────────────────────────────────────────────────────────────────────
function parseDurationMinutes(): number | null {
  const arg = process.argv.find((a) => a.startsWith('--duration-minutes='));
  if (!arg) return null;
  const n = Number(arg.split('=')[1]);
  return Number.isFinite(n) && n > 0 ? n : null;
}

const DURATION_MINUTES = parseDurationMinutes(); // null => run until killed
const CHECKPOINT_EVERY_MS = 5 * 60 * 1000;
const DATA_DIR = path.resolve(process.cwd(), 'data/stressRun');
const EVENTS_PATH = path.join(DATA_DIR, 'events.jsonl');
const CHECKPOINTS_PATH = path.join(DATA_DIR, 'checkpoints.jsonl');

mkdirSync(DATA_DIR, { recursive: true });

// ── Real Ollama provider config, sourced entirely from env (no hardcoded values) ────────────────
function buildOllamaConfig(): ProviderCallConfig {
  const model = process.env.REASONING_MODEL;
  const apiKey = process.env.OLLAMA_API_KEY;
  const baseUrlEnv = process.env.OLLAMA_BASE_URL;
  if (!model) throw new Error('REASONING_MODEL env var is required for the real-Ollama stress harness');
  if (!apiKey) throw new Error('OLLAMA_API_KEY env var is required for the real-Ollama stress harness');
  if (!baseUrlEnv) throw new Error('OLLAMA_BASE_URL env var is required for the real-Ollama stress harness');
  return {
    provider: 'ollama',
    model,
    apiKey,
    baseUrl: baseUrlEnv,
    temperature: Number(process.env.REASONING_TEMPERATURE ?? 0.2),
    maxTokens: Number(process.env.REASONING_MAX_TOKENS ?? 4000),
    timeoutMs: Number(process.env.REASONING_TIMEOUT_MS ?? 30_000),
    maxRetries: Number(process.env.REASONING_MAX_RETRIES ?? 2),
    structuredOutput: (process.env.REASONING_STRUCTURED_OUTPUT ?? 'true') === 'true',
  };
}

// ── Types ────────────────────────────────────────────────────────────────────────────────────
const PIPELINE_STAGES = [
  'context', 'memory', 'reasoningContext', 'prompt', 'decisionIntelligence',
  'decisionVerification', 'executionPlan', 'route', 'executionResult',
  'outcomeRecord', 'memoryWrite', 'learningSnapshot',
] as const;
type PipelineStage = (typeof PIPELINE_STAGES)[number];

type FailureCategory =
  | 'provider_timeout' | 'provider_unavailable' | 'malformed_json'
  | 'verification_rejected' | 'no_route' | 'unknown';

interface StressEvent {
  ts: string;
  iteration: number;
  ok: boolean;
  stageTimingsMs: Record<string, number>;
  totalDurationMs: number;
  failedStage?: string;
  failureCategory?: FailureCategory;
  errorName?: string;
  errorMessage?: string;
  rssMB: number;
  heapUsedMB: number;
  promptTokens?: number;
  completionTokens?: number;
  retryCount?: number;
}

function categorizeFailure(errorName: string, errorMessage: string, failedStage: PipelineStage | 'unknown'): FailureCategory {
  const name = errorName.toLowerCase();
  const msg = errorMessage.toLowerCase();
  if (failedStage === 'decisionVerification') return 'verification_rejected';
  if (failedStage === 'route' && msg.includes('no routable')) return 'no_route';
  if (name === 'providererror') {
    if (msg.includes('timed out') || msg.includes('timeout')) return 'provider_timeout';
    if (msg.includes('unavailable') || msg.includes('network') || /http 5\d\d/.test(msg)) return 'provider_unavailable';
    if (msg.includes('json') || msg.includes('parse') || /http \d\d\d: <!doctype/i.test(msg)) return 'malformed_json';
  }
  if (name.includes('malformeddecisionintelligence')) return 'malformed_json';
  return 'unknown';
}

function memUsageMB(): { rssMB: number; heapUsedMB: number } {
  const m = process.memoryUsage();
  return { rssMB: m.rss / (1024 * 1024), heapUsedMB: m.heapUsed / (1024 * 1024) };
}

function freshMemoryProviders(): WriteMemoryProviders {
  return { episodic: new InMemoryEpisodicProvider(), semantic: new InMemorySemanticProvider(), working: new InMemoryWorkingProvider() };
}

async function timeStage<T>(timings: Record<string, number>, stage: PipelineStage, fn: () => T | Promise<T>): Promise<T> {
  const start = performance.now();
  const result = await fn();
  timings[stage] = performance.now() - start;
  return result;
}

// ── One iteration of the real pipeline (adapted from benchmarks/e2e/pipeline.ts) ────────────────
async function runOneIteration(
  fixtures: PipelineFixtures,
  ollamaConfig: ProviderCallConfig,
  iteration: number
): Promise<StressEvent> {
  const now = Date.now();
  const agentId = fixtures.agentContext.agentId;
  const timings: Record<string, number> = {};
  const overallStart = performance.now();
  let currentStage: PipelineStage | 'unknown' = 'unknown';
  // generateDecisionIntelligence's returned DecisionIntelligenceMetadata does not expose
  // promptTokens/completionTokens/retryCount (those live in providers/ observability, recorded
  // internally via recordDecisionIntelligenceCall — not part of its public return shape), so
  // these stay undefined here rather than fabricated.
  const promptTokens: number | undefined = undefined;
  const completionTokens: number | undefined = undefined;
  const retryCount: number | undefined = undefined;

  try {
    const registry = buildProtocolRegistry();

    currentStage = 'context';
    const agentContextHash = await timeStage(timings, 'context', () => sha256(fixtures.agentContext));

    currentStage = 'memory';
    const memoryHash = await timeStage(timings, 'memory', () => sha256(fixtures.memoryPackage));

    currentStage = 'reasoningContext';
    const reasoningContext = await timeStage(timings, 'reasoningContext', () =>
      buildReasoningContext(fixtures.agentContext, fixtures.memoryPackage, fixtures.userPolicy));

    currentStage = 'prompt';
    const prompt = await timeStage(timings, 'prompt', () => buildPrompt(reasoningContext, 'v2'));

    currentStage = 'decisionIntelligence';
    const { decision } = await timeStage(timings, 'decisionIntelligence', () =>
      generateDecisionIntelligence(reasoningContext, prompt, ollamaConfig));

    currentStage = 'decisionVerification';
    const verification = await timeStage(timings, 'decisionVerification', () => verifyDecision(decision, reasoningContext, { now }));
    if (verification.status !== 'verified') {
      throw Object.assign(new Error(`decision rejected at verification: ${verification.failedRules.join('; ')}`), { name: 'VerificationRejected' });
    }

    currentStage = 'executionPlan';
    const plan = await timeStage(timings, 'executionPlan', () => buildExecutionPlan(verification, reasoningContext));

    currentStage = 'route';
    const routes = await timeStage(timings, 'route', () =>
      computeRoutesForPlan(plan, registry, {
        network: 'testnet',
        now: () => now,
        outputAssetFor: () => FIXTURE_OUTPUT_ASSET,
        adapterParamsFor: () => ({ trustlineEstablished: true, deadline: now + 3_600_000, minOutput: '0.001' }),
      }));
    if (routes.length === 0) {
      throw Object.assign(new Error('no routable step in plan (decision action produced no execute step)'), { name: 'NoRoute' });
    }
    const route = routes[0].route;

    currentStage = 'executionResult';
    const executionResult = await timeStage(timings, 'executionResult', () => executeRoute(plan, route, registry, { now: () => now }));

    currentStage = 'outcomeRecord';
    const outcomeRecord = await timeStage(timings, 'outcomeRecord', () =>
      recordOutcome(executionResult, {
        transactionHash: 'a'.repeat(64),
        transactionXDRHash: 'b'.repeat(64),
        amountRequested: '10.000000',
        amountExecuted: '9.990000',
        fees: '0.010000',
        slippage: 0.1,
        priceImpact: 0.05,
        balancesBefore: [{ asset: FIXTURE_ASSET, amount: '1000.000000' }],
        balancesAfter: [{ asset: FIXTURE_ASSET, amount: '990.000000' }],
        verificationHash: verification.verificationHash,
        contextHash: agentContextHash,
        memoryHash,
      }));

    currentStage = 'memoryWrite';
    await timeStage(timings, 'memoryWrite', () => writeMemory(outcomeRecord, { agentId, timestamp: now }, freshMemoryProviders()));

    currentStage = 'learningSnapshot';
    await timeStage(timings, 'learningSnapshot', () => computeLearningSnapshot(fixtures.memoryPackage));

    const { rssMB, heapUsedMB } = memUsageMB();
    return {
      ts: new Date().toISOString(), iteration, ok: true, stageTimingsMs: timings,
      totalDurationMs: performance.now() - overallStart, rssMB, heapUsedMB,
      promptTokens, completionTokens, retryCount,
    };
  } catch (err) {
    const e = err as Error;
    const errorName = e?.name ?? 'Error';
    const errorMessage = e?.message ?? String(err);
    const { rssMB, heapUsedMB } = memUsageMB();
    return {
      ts: new Date().toISOString(), iteration, ok: false,
      stageTimingsMs: timings, totalDurationMs: performance.now() - overallStart,
      failedStage: currentStage, failureCategory: categorizeFailure(errorName, errorMessage, currentStage),
      errorName, errorMessage, rssMB, heapUsedMB, promptTokens, completionTokens, retryCount,
    };
  }
}

// ── Checkpointing ────────────────────────────────────────────────────────────────────────────
interface CheckpointStats {
  ts: string;
  totalIterations: number;
  successCount: number;
  failureCount: number;
  failuresByCategory: Record<string, number>;
  latencyStats: { avgMs: number; p95Ms: number; p99Ms: number };
  avgRssMB: number;
  maxRssMB: number;
}

function percentile(sorted: number[], p: number): number {
  if (sorted.length === 0) return 0;
  const idx = Math.min(sorted.length - 1, Math.floor(p * sorted.length));
  return sorted[idx];
}

function computeCheckpoint(events: StressEvent[]): CheckpointStats {
  const totalIterations = events.length;
  const successCount = events.filter((e) => e.ok).length;
  const failureCount = totalIterations - successCount;
  const failuresByCategory: Record<string, number> = {};
  for (const e of events) {
    if (!e.ok && e.failureCategory) failuresByCategory[e.failureCategory] = (failuresByCategory[e.failureCategory] ?? 0) + 1;
  }
  const durations = events.map((e) => e.totalDurationMs).sort((a, b) => a - b);
  const avgMs = durations.length ? durations.reduce((a, b) => a + b, 0) / durations.length : 0;
  const rssValues = events.map((e) => e.rssMB);
  const avgRssMB = rssValues.length ? rssValues.reduce((a, b) => a + b, 0) / rssValues.length : 0;
  const maxRssMB = rssValues.length ? Math.max(...rssValues) : 0;
  return {
    ts: new Date().toISOString(),
    totalIterations, successCount, failureCount, failuresByCategory,
    latencyStats: { avgMs, p95Ms: percentile(durations, 0.95), p99Ms: percentile(durations, 0.99) },
    avgRssMB, maxRssMB,
  };
}

function appendJsonl(filePath: string, obj: unknown): void {
  appendFileSync(filePath, JSON.stringify(obj) + '\n');
}

// ── Main loop ────────────────────────────────────────────────────────────────────────────────
async function main() {
  const ollamaConfig = buildOllamaConfig();
  console.log(`[longRunStress] starting — provider=ollama model=${ollamaConfig.model} baseUrl=${ollamaConfig.baseUrl} durationMinutes=${DURATION_MINUTES ?? 'unbounded (run until killed)'}`);
  console.log(`[longRunStress] events -> ${EVENTS_PATH}`);
  console.log(`[longRunStress] checkpoints -> ${CHECKPOINTS_PATH}`);
  console.log('[longRunStress] NOTE: execution/route/outcome stages use the synthetic e2e protocol registry (benchmarks/e2e/registry.ts) — no real Stellar broadcast occurs. Only decisionIntelligence hits the real Ollama endpoint.');

  const fixtures = buildFixtures();
  const startTime = Date.now();
  const endTime = DURATION_MINUTES !== null ? startTime + DURATION_MINUTES * 60 * 1000 : Infinity;

  let iteration = 0;
  let lastCheckpointTime = Date.now();
  let sinceLastCheckpoint: StressEvent[] = [];
  let shuttingDown = false;

  const flushCheckpoint = () => {
    if (sinceLastCheckpoint.length === 0) return;
    const checkpoint = computeCheckpoint(sinceLastCheckpoint);
    appendJsonl(CHECKPOINTS_PATH, checkpoint);
    console.log(`[longRunStress] checkpoint @ ${checkpoint.ts}: iterations=${checkpoint.totalIterations} success=${checkpoint.successCount} failure=${checkpoint.failureCount} avgLatencyMs=${checkpoint.latencyStats.avgMs.toFixed(1)} p95Ms=${checkpoint.latencyStats.p95Ms.toFixed(1)} maxRssMB=${checkpoint.maxRssMB.toFixed(1)}`);
    sinceLastCheckpoint = [];
    lastCheckpointTime = Date.now();
  };

  const shutdown = (signal: string) => {
    if (shuttingDown) return;
    shuttingDown = true;
    console.log(`[longRunStress] received ${signal} — flushing final checkpoint and exiting`);
    flushCheckpoint();
    process.exit(0);
  };
  process.on('SIGTERM', () => shutdown('SIGTERM'));
  process.on('SIGINT', () => shutdown('SIGINT'));

  while (!shuttingDown && Date.now() < endTime) {
    iteration += 1;
    const event = await runOneIteration(fixtures, ollamaConfig, iteration);
    appendJsonl(EVENTS_PATH, event);
    sinceLastCheckpoint.push(event);

    if (event.ok) {
      console.log(`[longRunStress] iter=${iteration} ok totalMs=${event.totalDurationMs.toFixed(1)} diMs=${(event.stageTimingsMs.decisionIntelligence ?? 0).toFixed(1)} promptTok=${event.promptTokens ?? '-'} compTok=${event.completionTokens ?? '-'} rssMB=${event.rssMB.toFixed(1)}`);
    } else {
      console.log(`[longRunStress] iter=${iteration} FAIL stage=${event.failedStage} category=${event.failureCategory} error=${event.errorName}: ${event.errorMessage}`);
    }

    if (Date.now() - lastCheckpointTime >= CHECKPOINT_EVERY_MS) {
      flushCheckpoint();
    }
  }

  flushCheckpoint();
  console.log(`[longRunStress] done — ${iteration} iterations over ${((Date.now() - startTime) / 1000).toFixed(1)}s`);
}

main().catch((err) => {
  console.error('[longRunStress] fatal error outside iteration loop:', err);
  process.exit(1);
});
